# Entfernenn Sie das '#' in der nächsten Zeile, um Compileroptimierungen
# einzuschalten.
#OPT = -O

integrate: integrate.cpp
	g++ $(OPT) -fopenmp -o integrate integrate.cpp

clean:
	rm -f *.o *~ integrate
 
